Machine.add( "grain ck.ck" );
Std.rand2f(5,20)::ms=>now;
Machine.add( "grain ck.ck" );
Std.rand2f(5,20)::ms=>now;
Machine.add( "grain ck.ck" );
Std.rand2f(5,20)::ms=>now;
Machine.add( "grain ck.ck" );
Std.rand2f(5,20)::ms=>now;
Machine.add( "grain ck.ck" );
Std.rand2f(5,20)::ms=>now;
Machine.add( "grain ck.ck" );
Std.rand2f(5,20)::ms=>now;
Machine.add( "grain ck.ck" );